// RegKeyToMOF by Mark Cochrane (with help from Skissinger, SteveRac, Jonas Hettich, Kent Agerlund & Barker)
// this section tells the inventory agent what to report to the server
// 07/10/2021 11:20:12

#pragma namespace ("\\\\.\\root\\cimv2\\SMS")
#pragma deleteclass("COTwentyOneHTwoCM", NOFAIL)
[SMS_Report(TRUE),SMS_Group_Name("COTwentyOneHTwoCM"),SMS_Class_ID("COTwentyOneHTwoCM")]
Class COTwentyOneHTwoCM: SMS_Class_Template
{
[SMS_Report(TRUE),key] string KeyName;
[SMS_Report(TRUE)] String BlockedByBdd;
[SMS_Report(TRUE)] String BlockedByBios;
[SMS_Report(TRUE)] String BlockedByCloverTrail;
[SMS_Report(TRUE)] String BlockedByComputerHardwareId;
[SMS_Report(TRUE)] String BlockedByCpu;
[SMS_Report(TRUE)] String BlockedByCpuFms;
[SMS_Report(TRUE)] String BlockedByDeviceBlock;
[SMS_Report(TRUE)] String BlockedByHardDiskController;
[SMS_Report(TRUE)] String BlockedByMemory;
[SMS_Report(TRUE)] String BlockedByNetwork;
[SMS_Report(TRUE)] String BlockedBySModeState;
[SMS_Report(TRUE)] String BlockedBySystemDriveSize;
[SMS_Report(TRUE)] String BlockedBySystemDriveTooFull;
[SMS_Report(TRUE)] String BlockedByTpmVersion;
[SMS_Report(TRUE)] String BlockedByUefiSecureBoot;
[SMS_Report(TRUE)] String BlockedByUpgradableBios;
[SMS_Report(TRUE)] String Dx12SupportedDevice;
[SMS_Report(TRUE)] String RAV;
[SMS_Report(TRUE)] String Guest;
[SMS_Report(TRUE)] String MediaCenterInUse;
[SMS_Report(TRUE)] String UexRatingOrange;
[SMS_Report(TRUE)] String UexRatingRed;
[SMS_Report(TRUE)] String UexRatingYellow;
[SMS_Report(TRUE)] String UexUsageRatingOrange;
[SMS_Report(TRUE)] String UexUsageRatingYellow;
[SMS_Report(TRUE)] String Version;
[SMS_Report(TRUE)] String TimestampEpochString;
[SMS_Report(TRUE)] Uint64 Timestamp;
};