##############################################################################################################
## Script to create compatibility collections in MEMCM for Windows 10 22H2 based on custom inventoried data ##
##############################################################################################################

# Windows 10 Version
$W10Version = "22H2"

# Limiting collection
$LimitingCollection = "All Systems"

# Import ConfigMgr Module
Import-Module $env:SMS_ADMIN_UI_PATH.Replace('i386','ConfigurationManager.psd1')
$SiteCode = (Get-PSDrive -PSProvider CMSITE).Name
Set-Location ("$SiteCode" + ":")

# Collection names and query rules
$Collections = [ordered]@{
    "Windows 10 $W10Version Blocked: BDD" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByBdd = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: Bios" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByBios = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: ComputerHardwareId" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByComputerHardwareId = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: CPU" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByCpu = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: CPUFms" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByCpuFms = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: DeviceBlock" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByDeviceBlock = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: HardDiskController" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByHardDiskController = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: Memory" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByMemory = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: Network" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByNetwork = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: Safeguard Hold Any" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.GatedBlockId != ""None"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: Safeguard Hold Id 40667045" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.GatedBlockId = ""40667045"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: Safeguard Hold Id 41291788" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.GatedBlockId = ""41291788"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: SModeState" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedBySModeState = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: SystemDriveSize" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedBySystemDriveSize = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: SystemDriveTooFull" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedBySystemDriveTooFull = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: TPMversion" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceId = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByTpmVersion = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: UefiSecureBoot" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByUefiSecureBoot = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Blocked: UpgradeableBios" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.BlockedByUpgradableBios = ""1"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Capable" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceId = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.RedReason = ""None"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"" and SMS_G_System_NITwentyTwoHTwo.GatedBlockId = ""None"""
    "Windows 10 $W10Version FailedPrereqs" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceId = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.FailedPrereqs != ""None"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version Has Red Reason" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.RedReason != ""None"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version UEX Rating Orange" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.UexRatingOrange > ""0"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version UEX Rating Red" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.UexRatingRed > ""0"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version UEX Rating Yellow" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwoCM on SMS_G_System_NITwentyTwoHTwoCM.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwoCM.UexRatingYellow > ""0"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version UEX: Green" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.UpgEx = ""Green"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version UEX: Orange" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.UpgEx = ""Orange"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version UEX: Red" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.UpgEx = ""Red"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
    "Windows 10 $W10Version UEX: Yellow" = "select SMS_R_SYSTEM.ResourceID,SMS_R_SYSTEM.ResourceType,SMS_R_SYSTEM.Name,SMS_R_SYSTEM.SMSUniqueIdentifier,SMS_R_SYSTEM.ResourceDomainORWorkgroup,SMS_R_SYSTEM.Client from SMS_R_System inner join SMS_G_System_OPERATING_SYSTEM on SMS_G_System_OPERATING_SYSTEM.ResourceId = SMS_R_System.ResourceId inner join SMS_G_System_NITwentyTwoHTwo on SMS_G_System_NITwentyTwoHTwo.ResourceID = SMS_R_System.ResourceId where SMS_G_System_NITwentyTwoHTwo.UpgEx = ""Yellow"" and SMS_G_System_OPERATING_SYSTEM.Caption like ""Microsoft Windows 10%"""
}

# Create the collections
foreach ($CollectionName in $Collections.Keys)
{
    Write-host "Creating collection: '$CollectionName'"
    $Query = $Collections["$CollectionName"]
    $Collection = New-CMDeviceCollection -LimitingCollectionName $LimitingCollection -Name $CollectionName -RefreshType Periodic -RefreshSchedule (Convert-CMSchedule -ScheduleString "920A8C0000100008")
    Add-CMDeviceCollectionQueryMembershipRule -CollectionName $Collection.Name -QueryExpression $Query -RuleName "$($Collection.Name)"
}

# Include collection names for the 'Not capable' collection
$IncludeCollections = @(
    "Windows 10 $W10Version Blocked: TPMversion"
    "Windows 10 $W10Version Blocked: BDD"
    "Windows 10 $W10Version Blocked: Bios"
    "Windows 10 $W10Version Blocked: SystemDriveSize"
    "Windows 10 $W10Version Blocked: ComputerHardwareId"
    "Windows 10 $W10Version Blocked: CPU"
    "Windows 10 $W10Version Blocked: CPUFms"
    "Windows 10 $W10Version Blocked: DeviceBlock"
    "Windows 10 $W10Version Blocked: HardDiskController"
    "Windows 10 $W10Version Blocked: Memory"
    "Windows 10 $W10Version Blocked: Network"
    "Windows 10 $W10Version Blocked: SModeState"
    "Windows 10 $W10Version Blocked: SystemDriveTooFull"
    "Windows 10 $W10Version Blocked: UefiSecureBoot"
    "Windows 10 $W10Version Blocked: UpgradeableBios"
    "Windows 10 $W10Version FailedPrereqs"
    "Windows 10 $W10Version Blocked: Safeguard Hold Any"
)
# Create the 'Not capable' collection
$NotCapable = "Windows 10 $W10Version Not Capable"
Write-host "Creating and adding include collections for 'Windows 10 $W10Version Not Capable'"
$Collection = New-CMDeviceCollection -LimitingCollectionName $LimitingCollection -Name $NotCapable -RefreshType Periodic -RefreshSchedule (Convert-CMSchedule -ScheduleString "920A8C0000100008")
foreach ($IncludeCollection in $IncludeCollections)
{
    Add-CMDeviceCollectionIncludeMembershipRule -CollectionName "Windows 10 $W10Version Not Capable" -IncludeCollectionName $IncludeCollection
}
